import pandas as pd
from rdkit import Chem
from rdkit.Chem import rdfiltercatalog

# Define the input file path
input_file = 'nvik_final_indexed.smi'

# Read the SMILES from the .smi file
smiles_data = []
with open(input_file, 'r') as file:
    for line in file:
        parts = line.strip().split('\t')
        if len(parts) == 2:
            smiles_data.append(parts)

# Initialize the filter catalog with FilterCatalogs.ALL
filter_catalog_params = rdfiltercatalog.FilterCatalogParams()
filter_catalog_params.AddCatalog(rdfiltercatalog.FilterCatalogParams.FilterCatalogs.PAINS)
filter_catalog = rdfiltercatalog.FilterCatalog(filter_catalog_params)


# Process each SMILES and calculate the PAINS filter
results = []
for identifier, smiles in smiles_data:
    mol = Chem.MolFromSmiles(smiles)
    if mol is not None:
        pains_match = filter_catalog.HasMatch(mol)
        results.append([identifier, smiles, pains_match])
    else:
        results.append([identifier, smiles, 'Invalid SMILES'])

# Create a DataFrame from the results
df = pd.DataFrame(results, columns=['Identifier', 'SMILES', 'PAINS Filter'])

# Save the output to a CSV file
output_file = 'pains_filter_results-nvik-final_indexed.csv'
df.to_csv(output_file, index=False)

print(f"PAINS filter results saved to {output_file}")


#The above code was partially generated by Claude, an AI assistant created by Anthropic.
#It has been modified and verified for use in this project.