import pandas as pd
from rdkit import Chem
from rdkit.Chem import Descriptors, rdMolDescriptors

# Define the path to your CSV file
input_csv_file = 'nvik_indexed.csv'
output_excel_file = 'nvik_indexed_calculated_properties.xlsx'

# Read the CSV file
df = pd.read_csv(input_csv_file)

# Define a function to calculate properties
def calculate_properties(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol:
        return {
            'Molecular Weight': Descriptors.MolWt(mol),
            'HB Acceptors': Descriptors.NumHAcceptors(mol),
            'HB Donors': Descriptors.NumHDonors(mol),
            'Rotatable Bonds': Descriptors.NumRotatableBonds(mol),
            'LogP': Descriptors.MolLogP(mol),
            'TPSA': Descriptors.TPSA(mol),
#            'Aliphatic or Cyclic': "Aliphatic" if rdMolDescriptors.CalcNumAliphaticRings(mol) > 0 else "Cyclic"
            'Aliphatic or Cyclic': 'Aliphatic' if rdMolDescriptors.CalcNumRings(mol) == 0 else 'Cyclic'

        }
    else:
        return {prop: None for prop in ['Molecular Weight', 'HB Acceptors', 'HB Donors', 'Rotatable Bonds', 'LogP', 'TPSA', 'Aliphatic or Cyclic']}

# Apply the function to calculate properties for each SMILES string
properties_df = df['smiles'].apply(lambda x: pd.Series(calculate_properties(x)))

# Combine the original DataFrame with the properties DataFrame
result_df = pd.concat([df['nvic id'], properties_df], axis=1)

# Save the results to a new CSV file
result_df.to_excel(output_excel_file, index=False)

print("Properties calculated and saved successfully")

#The above code was partially generated by Claude, an AI assistant created by Anthropic.
#It has been modified and verified for use in this project.